import {
  View,
  Text,
  TouchableOpacity,
  ScrollView,
  StyleSheet,
  Image,
  Switch,
  Share,
  Alert,
  TextInput,
  ActivityIndicator,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useState, useEffect, useRef } from 'react';
import * as ImagePicker from 'expo-image-picker';
import * as ImageManipulator from 'expo-image-manipulator';
import * as FileSystem from 'expo-file-system';
import { useAuth } from '../../context/AuthContext';
import { useSettings } from '../../context/SettingsContext';
import { tripsAPI, usersAPI } from '../../services/api';
import SwipeableBottomSheet from '../../components/SwipeableBottomSheet';
import { spacing, shadows, borderRadius } from '../../styles/theme';

export default function ProfileScreen() {
  const { user, logout, updateUser } = useAuth();
  const { darkMode, toggleDarkMode, currency, updateCurrency, currencies, colors, typography, chatMode, toggleChatMode } = useSettings();
  const [trips, setTrips] = useState([]);
  const [showCurrencyPicker, setShowCurrencyPicker] = useState(false);
  const [showAbout, setShowAbout] = useState(false);

  // Username edit state
  const [showUsernameEdit, setShowUsernameEdit] = useState(false);
  const [usernameInput, setUsernameInput] = useState('');
  const [usernameAvailability, setUsernameAvailability] = useState(null); // null | 'checking' | 'available' | 'taken' | 'invalid'
  const [usernameSaving, setUsernameSaving] = useState(false);
  const usernameDebounceRef = useRef(null);

  // Avatar picker state
  const [showAvatarPicker, setShowAvatarPicker] = useState(false);
  const [avatarUploading, setAvatarUploading] = useState(false);

  useEffect(() => {
    loadTrips();
  }, []);

  const loadTrips = async () => {
    try {
      const res = await tripsAPI.getAll();
      setTrips(res.data.trips || []);
    } catch (e) {
      // silent
    }
  };

  // Calculate real stats
  const totalTrips = trips.length;
  const uniqueCountries = new Set(trips.map((t) => t.destination?.country).filter(Boolean)).size;
  const totalDays = trips.reduce((sum, t) => sum + (t.days || 0), 0);

  const stats = [
    { label: 'Trips', value: totalTrips, icon: 'airplane' },
    { label: 'Countries', value: uniqueCountries, icon: 'globe' },
    { label: 'Days', value: totalDays, icon: 'calendar' },
  ];

  const handleExport = async () => {
    if (trips.length === 0) {
      Alert.alert('No Trips', 'Create some trips first to export them.');
      return;
    }

    let exportText = '✈️ My TripCraft Trips\n';
    exportText += '━━━━━━━━━━━━━━━━━━━\n\n';

    trips.forEach((trip, idx) => {
      const arrival = trip.arrivalDate
        ? new Date(trip.arrivalDate).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })
        : '';
      const departure = trip.departureDate
        ? new Date(trip.departureDate).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })
        : '';

      exportText += `${idx + 1}. ${trip.destination?.name || 'Unknown'}`;
      if (trip.destination?.country) exportText += `, ${trip.destination.country}`;
      exportText += '\n';
      exportText += `   📅 ${arrival} - ${departure} (${trip.days} days)\n`;
      exportText += `   💰 ${trip.budget?.amount} ${trip.budget?.currency || 'USD'}\n`;
      if (trip.accommodation) exportText += `   🏨 ${trip.accommodation}\n`;
      if (trip.travelPace) exportText += `   🚀 ${trip.travelPace} pace\n`;
      if (trip.travelStyle?.length) exportText += `   🎯 ${trip.travelStyle.join(', ')}\n`;
      exportText += '\n';
    });

    exportText += `\n📊 Total: ${totalTrips} trips · ${uniqueCountries} countries · ${totalDays} days\n`;
    exportText += '\nGenerated by TripCraft - Your AI Travel Planner';

    try {
      await Share.share({
        message: exportText,
        title: 'My TripCraft Trips',
      });
    } catch (e) {
      // silent
    }
  };

  // ── Username helpers ──────────────────────────────────────────────────────

  const openUsernameEdit = () => {
    setUsernameInput(user?.username || '');
    setUsernameAvailability(null);
    setShowUsernameEdit(true);
  };

  const onUsernameChange = (text) => {
    // Only allow alphanumeric + underscores
    const cleaned = text.replace(/[^a-zA-Z0-9_]/g, '').toLowerCase();
    setUsernameInput(cleaned);

    if (usernameDebounceRef.current) clearTimeout(usernameDebounceRef.current);

    if (cleaned.length === 0) {
      setUsernameAvailability(null);
      return;
    }
    if (cleaned.length < 3) {
      setUsernameAvailability('invalid');
      return;
    }
    if (cleaned === user?.username) {
      setUsernameAvailability('available');
      return;
    }

    setUsernameAvailability('checking');
    usernameDebounceRef.current = setTimeout(async () => {
      try {
        const res = await usersAPI.checkUsername(cleaned);
        setUsernameAvailability(res.data.available ? 'available' : 'taken');
      } catch (e) {
        setUsernameAvailability(null);
      }
    }, 500);
  };

  const handleSaveUsername = async () => {
    if (usernameAvailability !== 'available') return;
    setUsernameSaving(true);
    try {
      await usersAPI.updateUsername(usernameInput);
      await updateUser({ username: usernameInput });
      setShowUsernameEdit(false);
    } catch (e) {
      Alert.alert('Error', 'Could not update username. Please try again.');
    } finally {
      setUsernameSaving(false);
    }
  };

  const getUsernameStatusIcon = () => {
    switch (usernameAvailability) {
      case 'checking':
        return <ActivityIndicator size="small" color={colors.textMuted} />;
      case 'available':
        return <Ionicons name="checkmark-circle" size={20} color="#22C55E" />;
      case 'taken':
        return <Ionicons name="close-circle" size={20} color={colors.error} />;
      case 'invalid':
        return <Ionicons name="alert-circle" size={20} color="#F59E0B" />;
      default:
        return null;
    }
  };

  const getUsernameStatusText = () => {
    switch (usernameAvailability) {
      case 'available':
        return { text: 'Username is available', color: '#22C55E' };
      case 'taken':
        return { text: 'Username is already taken', color: colors.error };
      case 'invalid':
        return { text: 'Must be at least 3 characters', color: '#F59E0B' };
      default:
        return null;
    }
  };

  // ── Avatar helpers ────────────────────────────────────────────────────────

  const pickAndUploadImage = async (source) => {
    setShowAvatarPicker(false);
    try {
      let result;
      if (source === 'camera') {
        const { status } = await ImagePicker.requestCameraPermissionsAsync();
        if (status !== 'granted') {
          Alert.alert('Permission Required', 'Camera access is needed to take a photo.');
          return;
        }
        result = await ImagePicker.launchCameraAsync({ allowsEditing: true, aspect: [1, 1], quality: 1 });
      } else {
        const { status } = await ImagePicker.requestMediaLibraryPermissionsAsync();
        if (status !== 'granted') {
          Alert.alert('Permission Required', 'Photo library access is needed to choose a photo.');
          return;
        }
        result = await ImagePicker.launchImageLibraryAsync({ allowsEditing: true, aspect: [1, 1], quality: 1, mediaTypes: ImagePicker.MediaTypeOptions.Images });
      }

      if (result.canceled) return;

      setAvatarUploading(true);

      // Resize to 150x150 and compress to 50% JPEG
      const manipulated = await ImageManipulator.manipulateAsync(
        result.assets[0].uri,
        [{ resize: { width: 150, height: 150 } }],
        { compress: 0.5, format: ImageManipulator.SaveFormat.JPEG }
      );

      // Convert to base64
      const base64 = await FileSystem.readAsStringAsync(manipulated.uri, {
        encoding: FileSystem.EncodingType.Base64,
      });
      const base64Uri = `data:image/jpeg;base64,${base64}`;

      await usersAPI.updateProfilePhoto(base64Uri);
      await updateUser({ avatar: base64Uri });
    } catch (e) {
      Alert.alert('Error', 'Could not update profile photo. Please try again.');
    } finally {
      setAvatarUploading(false);
    }
  };

  const handleRemovePhoto = async () => {
    setShowAvatarPicker(false);
    try {
      setAvatarUploading(true);
      await usersAPI.removeProfilePhoto();
      await updateUser({ avatar: '' });
    } catch (e) {
      Alert.alert('Error', 'Could not remove profile photo. Please try again.');
    } finally {
      setAvatarUploading(false);
    }
  };

  const s = getStyles(colors, typography);

  return (
    <SafeAreaView style={[s.container, { backgroundColor: colors.background }]}>
      <ScrollView showsVerticalScrollIndicator={false}>
        <View style={s.profileHeader}>
          {/* Tappable avatar with camera overlay */}
          <TouchableOpacity onPress={() => setShowAvatarPicker(true)} style={s.avatarWrapper}>
            <View style={[s.avatar, { backgroundColor: colors.primaryLight }]}>
              {avatarUploading ? (
                <ActivityIndicator size="large" color={colors.primary} />
              ) : user?.avatar ? (
                <Image source={{ uri: user.avatar }} style={s.avatarImage} />
              ) : (
                <Ionicons name="person" size={40} color={colors.textMuted} />
              )}
            </View>
            <View style={[s.cameraOverlay, { backgroundColor: colors.primary }]}>
              <Ionicons name="camera" size={12} color="#FFFFFF" />
            </View>
          </TouchableOpacity>

          <Text style={[s.name, { color: colors.textPrimary }]}>{user?.name || 'Traveler'}</Text>
          <Text style={[s.email, { color: colors.textSecondary }]}>{user?.email || ''}</Text>

          {/* Username row */}
          <TouchableOpacity onPress={openUsernameEdit} style={s.usernameRow}>
            <Text style={[s.usernameText, { color: colors.primary }]}>
              {user?.username ? `@${user.username}` : 'Set username'}
            </Text>
            <Ionicons name="pencil" size={13} color={colors.primary} style={{ marginLeft: 4 }} />
          </TouchableOpacity>
        </View>

        {/* Stats */}
        <View style={[s.statsCard, { backgroundColor: colors.card }]}>
          <Text style={[s.statsTitle, { color: colors.textSecondary }]}>Trip Stats</Text>
          <View style={s.statsRow}>
            {stats.map((stat) => (
              <View key={stat.label} style={s.statItem}>
                <Ionicons name={stat.icon} size={20} color={colors.primary} style={{ marginBottom: 4 }} />
                <Text style={[s.statValue, { color: colors.primary }]}>{stat.value}</Text>
                <Text style={[s.statLabel, { color: colors.textMuted }]}>{stat.label}</Text>
              </View>
            ))}
          </View>
        </View>

        {/* Settings */}
        <Text style={[s.sectionTitle, { color: colors.textSecondary }]}>Settings</Text>
        <View style={[s.menuCard, { backgroundColor: colors.card }]}>
          {/* Currency */}
          <TouchableOpacity style={[s.menuItem, s.menuItemBorder]} onPress={() => setShowCurrencyPicker(true)}>
            <Ionicons name="cash-outline" size={22} color={colors.textSecondary} />
            <Text style={[s.menuLabel, { color: colors.textPrimary }]}>Default Currency</Text>
            <Text style={[s.menuValue, { color: colors.textSecondary }]}>{currency}</Text>
            <Ionicons name="chevron-forward" size={18} color={colors.textMuted} />
          </TouchableOpacity>

          {/* Dark Mode */}
          <View style={[s.menuItem, s.menuItemBorder]}>
            <Ionicons name="moon-outline" size={22} color={colors.textSecondary} />
            <Text style={[s.menuLabel, { color: colors.textPrimary }]}>Dark Mode</Text>
            <Switch
              value={darkMode}
              onValueChange={toggleDarkMode}
              trackColor={{ false: colors.border, true: colors.primary }}
              thumbColor="#FFFFFF"
            />
          </View>

          {/* Notifications */}
          <View style={[s.menuItem, s.menuItemBorder]}>
            <Ionicons name="notifications-outline" size={22} color={colors.textSecondary} />
            <Text style={[s.menuLabel, { color: colors.textPrimary }]}>Notifications</Text>
            <Text style={[s.menuValue, { color: colors.textMuted }]}>Coming soon</Text>
          </View>

          {/* Chat Mode */}
          <View style={[s.menuItem, s.menuItemBorder]}>
            <Ionicons name="cloud-outline" size={22} color={colors.textSecondary} />
            <Text style={[s.menuLabel, { color: colors.textPrimary }]}>Chat Mode</Text>
            <Text style={[s.menuValue, { color: colors.textMuted }]}>
              {chatMode === 'online' ? 'Online' : 'Offline'}
            </Text>
            <Switch
              value={chatMode === 'online'}
              onValueChange={toggleChatMode}
              trackColor={{ false: colors.border, true: colors.primary }}
              thumbColor="#FFFFFF"
            />
          </View>

          {/* Export */}
          <TouchableOpacity style={s.menuItem} onPress={handleExport}>
            <Ionicons name="share-outline" size={22} color={colors.textSecondary} />
            <Text style={[s.menuLabel, { color: colors.textPrimary }]}>Export Trips</Text>
            <Ionicons name="chevron-forward" size={18} color={colors.textMuted} />
          </TouchableOpacity>
        </View>

        {/* About */}
        <View style={[s.menuCard, { backgroundColor: colors.card }]}>
          <TouchableOpacity style={[s.menuItem, s.menuItemBorder]} onPress={() => setShowAbout(true)}>
            <Ionicons name="information-circle-outline" size={22} color={colors.textSecondary} />
            <Text style={[s.menuLabel, { color: colors.textPrimary }]}>About TripCraft</Text>
            <Ionicons name="chevron-forward" size={18} color={colors.textMuted} />
          </TouchableOpacity>
          <TouchableOpacity style={[s.menuItem, s.menuItemBorder]} onPress={() => {
            Share.share({ message: 'Check out TripCraft - AI-powered solo travel planner! Plan your perfect trip in minutes.' });
          }}>
            <Ionicons name="chatbubble-outline" size={22} color={colors.textSecondary} />
            <Text style={[s.menuLabel, { color: colors.textPrimary }]}>Tell a Friend</Text>
            <Ionicons name="chevron-forward" size={18} color={colors.textMuted} />
          </TouchableOpacity>
          <TouchableOpacity style={s.menuItem} onPress={logout}>
            <Ionicons name="log-out-outline" size={22} color={colors.error} />
            <Text style={[s.menuLabel, { color: colors.error }]}>Log Out</Text>
          </TouchableOpacity>
        </View>

        <Text style={[s.version, { color: colors.textMuted }]}>TripCraft v1.0.0</Text>
        <View style={{ height: 100 }} />
      </ScrollView>

      {/* Currency Picker */}
      <SwipeableBottomSheet visible={showCurrencyPicker} onClose={() => setShowCurrencyPicker(false)} maxHeightRatio={0.6}>
        <Text style={[s.modalTitle, { color: colors.textPrimary }]}>Select Currency</Text>
        <ScrollView showsVerticalScrollIndicator={false}>
          {currencies.map((c) => (
            <TouchableOpacity
              key={c}
              style={[s.currencyItem, currency === c && { backgroundColor: colors.primaryLight }]}
              onPress={() => {
                updateCurrency(c);
                setShowCurrencyPicker(false);
              }}
            >
              <Text style={[s.currencyText, { color: colors.textPrimary }, currency === c && { color: colors.primary, fontWeight: '700' }]}>{c}</Text>
              {currency === c && <Ionicons name="checkmark" size={22} color={colors.primary} />}
            </TouchableOpacity>
          ))}
        </ScrollView>
      </SwipeableBottomSheet>

      {/* Username Edit Sheet */}
      <SwipeableBottomSheet visible={showUsernameEdit} onClose={() => setShowUsernameEdit(false)} maxHeightRatio={0.55}>
        <Text style={[s.modalTitle, { color: colors.textPrimary }]}>Edit Username</Text>

        {/* Input row */}
        <View style={[s.usernameInputRow, { borderColor: colors.border, backgroundColor: colors.backgroundSecondary || colors.background }]}>
          <Text style={[s.usernameAtSign, { color: colors.textMuted }]}>@</Text>
          <TextInput
            style={[s.usernameInput, { color: colors.textPrimary }]}
            value={usernameInput}
            onChangeText={onUsernameChange}
            placeholder="your_username"
            placeholderTextColor={colors.textMuted}
            autoCapitalize="none"
            autoCorrect={false}
            autoFocus
            maxLength={30}
          />
          <View style={s.usernameStatusIcon}>{getUsernameStatusIcon()}</View>
        </View>

        {/* Status text */}
        {getUsernameStatusText() && (
          <Text style={[s.usernameStatusText, { color: getUsernameStatusText().color }]}>
            {getUsernameStatusText().text}
          </Text>
        )}

        {/* Rules */}
        <Text style={[s.usernameRules, { color: colors.textMuted }]}>
          3–30 characters. Letters, numbers, and underscores only.
        </Text>

        {/* Save button */}
        <TouchableOpacity
          style={[
            s.saveButton,
            { backgroundColor: usernameAvailability === 'available' ? colors.primary : colors.border },
          ]}
          onPress={handleSaveUsername}
          disabled={usernameAvailability !== 'available' || usernameSaving}
        >
          {usernameSaving ? (
            <ActivityIndicator size="small" color="#FFFFFF" />
          ) : (
            <Text style={s.saveButtonText}>Save Username</Text>
          )}
        </TouchableOpacity>
      </SwipeableBottomSheet>

      {/* Avatar Picker Sheet */}
      <SwipeableBottomSheet visible={showAvatarPicker} onClose={() => setShowAvatarPicker(false)} maxHeightRatio={0.38}>
        <Text style={[s.modalTitle, { color: colors.textPrimary }]}>Profile Photo</Text>

        <TouchableOpacity style={[s.avatarOption, s.menuItemBorder, { borderBottomColor: colors.border }]} onPress={() => pickAndUploadImage('camera')}>
          <Ionicons name="camera-outline" size={22} color={colors.textSecondary} />
          <Text style={[s.avatarOptionText, { color: colors.textPrimary }]}>Take Photo</Text>
        </TouchableOpacity>

        <TouchableOpacity style={[s.avatarOption, s.menuItemBorder, { borderBottomColor: colors.border }]} onPress={() => pickAndUploadImage('gallery')}>
          <Ionicons name="image-outline" size={22} color={colors.textSecondary} />
          <Text style={[s.avatarOptionText, { color: colors.textPrimary }]}>Choose from Gallery</Text>
        </TouchableOpacity>

        <TouchableOpacity style={s.avatarOption} onPress={handleRemovePhoto}>
          <Ionicons name="trash-outline" size={22} color={colors.error} />
          <Text style={[s.avatarOptionText, { color: colors.error }]}>Remove Photo</Text>
        </TouchableOpacity>
      </SwipeableBottomSheet>

      {/* About */}
      <SwipeableBottomSheet visible={showAbout} onClose={() => setShowAbout(false)} maxHeightRatio={0.75}>
        <ScrollView showsVerticalScrollIndicator={false}>
          <View style={s.aboutHeader}>
            <View style={[s.aboutLogo, { backgroundColor: colors.primaryLight }]}>
              <Ionicons name="airplane" size={32} color={colors.primary} />
            </View>
            <Text style={[s.aboutTitle, { color: colors.textPrimary }]}>TripCraft</Text>
            <Text style={[s.aboutVersion, { color: colors.textMuted }]}>Version 1.0.0</Text>
          </View>
          <Text style={[s.aboutText, { color: colors.textSecondary }]}>
            TripCraft is your AI-powered solo travel companion. Plan perfect trips with personalized itineraries, smart budget tracking, interactive maps, and curated packing lists.
          </Text>
          <Text style={[s.aboutText, { color: colors.textSecondary, marginTop: spacing.md }]}>
            Built with React Native, Expo, Node.js, MongoDB, and OpenAI.
          </Text>
          <View style={s.aboutFeatures}>
            {[
              { icon: 'sparkles', text: 'AI-Generated Itineraries' },
              { icon: 'map', text: 'Interactive Maps' },
              { icon: 'wallet', text: 'Budget Tracking' },
              { icon: 'bag', text: 'Smart Packing Lists' },
              { icon: 'sunny', text: 'Weather Forecasts' },
              { icon: 'pencil', text: 'Edit & Customize' },
            ].map((f) => (
              <View key={f.text} style={s.aboutFeatureRow}>
                <Ionicons name={f.icon} size={18} color={colors.primary} />
                <Text style={[s.aboutFeatureText, { color: colors.textPrimary }]}>{f.text}</Text>
              </View>
            ))}
          </View>
        </ScrollView>
      </SwipeableBottomSheet>
    </SafeAreaView>
  );
}

const getStyles = (colors, typography) => StyleSheet.create({
  container: {
    flex: 1,
    padding: spacing.xl,
  },
  profileHeader: {
    alignItems: 'center',
    marginBottom: spacing.xxl,
  },
  avatarWrapper: {
    position: 'relative',
    marginBottom: spacing.md,
  },
  avatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarImage: {
    width: 80,
    height: 80,
    borderRadius: 40,
  },
  cameraOverlay: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 24,
    height: 24,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  name: {
    fontSize: 22,
    fontWeight: '700',
    marginBottom: spacing.xs,
  },
  email: {
    fontSize: 14,
    marginBottom: spacing.xs,
  },
  usernameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: spacing.xs,
  },
  usernameText: {
    fontSize: 14,
    fontWeight: '600',
  },
  statsCard: {
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
    marginBottom: spacing.xxl,
    ...shadows.card,
  },
  statsTitle: {
    fontSize: 14,
    fontWeight: '600',
    marginBottom: spacing.lg,
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  statItem: {
    alignItems: 'center',
  },
  statValue: {
    fontSize: 22,
    fontWeight: '700',
  },
  statLabel: {
    fontSize: 12,
    marginTop: spacing.xs,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '600',
    marginBottom: spacing.md,
  },
  menuCard: {
    borderRadius: borderRadius.lg,
    marginBottom: spacing.lg,
    ...shadows.card,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: spacing.lg,
    gap: spacing.md,
  },
  menuItemBorder: {
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  menuLabel: {
    fontSize: 16,
    flex: 1,
  },
  menuValue: {
    fontSize: 14,
    marginRight: spacing.sm,
  },
  version: {
    textAlign: 'center',
    fontSize: 12,
    marginTop: spacing.md,
  },
  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  modalSheet: {
    borderTopLeftRadius: borderRadius.xl,
    borderTopRightRadius: borderRadius.xl,
    padding: spacing.xl,
    maxHeight: '80%',
  },
  modalHandle: {
    width: 40,
    height: 4,
    backgroundColor: '#E5E7EB',
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: spacing.lg,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '700',
    marginBottom: spacing.lg,
  },
  currencyItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: spacing.lg,
    borderRadius: borderRadius.md,
    marginBottom: spacing.xs,
  },
  currencyText: {
    fontSize: 16,
  },
  modalCancel: {
    alignItems: 'center',
    paddingVertical: spacing.lg,
    marginTop: spacing.md,
  },
  modalCancelText: {
    fontSize: 16,
    fontWeight: '600',
  },
  // Username edit sheet
  usernameInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1.5,
    borderRadius: borderRadius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    marginBottom: spacing.sm,
  },
  usernameAtSign: {
    fontSize: 18,
    fontWeight: '600',
    marginRight: 2,
  },
  usernameInput: {
    flex: 1,
    fontSize: 16,
    paddingVertical: spacing.xs,
  },
  usernameStatusIcon: {
    width: 24,
    alignItems: 'center',
  },
  usernameStatusText: {
    fontSize: 13,
    marginBottom: spacing.xs,
  },
  usernameRules: {
    fontSize: 12,
    marginBottom: spacing.lg,
  },
  saveButton: {
    borderRadius: borderRadius.md,
    paddingVertical: spacing.md,
    alignItems: 'center',
    marginTop: spacing.sm,
  },
  saveButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  // Avatar picker sheet
  avatarOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing.lg,
    gap: spacing.md,
  },
  avatarOptionText: {
    fontSize: 16,
  },
  // About
  aboutHeader: {
    alignItems: 'center',
    marginBottom: spacing.xxl,
  },
  aboutLogo: {
    width: 64,
    height: 64,
    borderRadius: 32,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  aboutTitle: {
    fontSize: 24,
    fontWeight: '700',
  },
  aboutVersion: {
    fontSize: 14,
    marginTop: spacing.xs,
  },
  aboutText: {
    fontSize: 14,
    lineHeight: 22,
    textAlign: 'center',
  },
  aboutFeatures: {
    marginTop: spacing.xxl,
    gap: spacing.md,
  },
  aboutFeatureRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
  },
  aboutFeatureText: {
    fontSize: 15,
  },
});
