import { View, Text, TouchableOpacity, ScrollView, StyleSheet, Image, Switch, Share, Alert } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useState, useEffect } from 'react';
import { useAuth } from '../../context/AuthContext';
import { useSettings } from '../../context/SettingsContext';
import { tripsAPI } from '../../services/api';
import SwipeableBottomSheet from '../../components/SwipeableBottomSheet';
import { spacing, shadows, borderRadius } from '../../styles/theme';

export default function ProfileScreen() {
  const { user, logout } = useAuth();
  const { darkMode, toggleDarkMode, currency, updateCurrency, currencies, colors, typography } = useSettings();
  const [trips, setTrips] = useState([]);
  const [showCurrencyPicker, setShowCurrencyPicker] = useState(false);
  const [showAbout, setShowAbout] = useState(false);

  useEffect(() => {
    loadTrips();
  }, []);

  const loadTrips = async () => {
    try {
      const res = await tripsAPI.getAll();
      setTrips(res.data.trips || []);
    } catch (e) {
      // silent
    }
  };

  // Calculate real stats
  const totalTrips = trips.length;
  const uniqueCountries = new Set(trips.map((t) => t.destination?.country).filter(Boolean)).size;
  const totalDays = trips.reduce((sum, t) => sum + (t.days || 0), 0);

  const stats = [
    { label: 'Trips', value: totalTrips, icon: 'airplane' },
    { label: 'Countries', value: uniqueCountries, icon: 'globe' },
    { label: 'Days', value: totalDays, icon: 'calendar' },
  ];

  const handleExport = async () => {
    if (trips.length === 0) {
      Alert.alert('No Trips', 'Create some trips first to export them.');
      return;
    }

    let exportText = '✈️ My TripCraft Trips\n';
    exportText += '━━━━━━━━━━━━━━━━━━━\n\n';

    trips.forEach((trip, idx) => {
      const arrival = trip.arrivalDate
        ? new Date(trip.arrivalDate).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })
        : '';
      const departure = trip.departureDate
        ? new Date(trip.departureDate).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })
        : '';

      exportText += `${idx + 1}. ${trip.destination?.name || 'Unknown'}`;
      if (trip.destination?.country) exportText += `, ${trip.destination.country}`;
      exportText += '\n';
      exportText += `   📅 ${arrival} - ${departure} (${trip.days} days)\n`;
      exportText += `   💰 ${trip.budget?.amount} ${trip.budget?.currency || 'USD'}\n`;
      if (trip.accommodation) exportText += `   🏨 ${trip.accommodation}\n`;
      if (trip.travelPace) exportText += `   🚀 ${trip.travelPace} pace\n`;
      if (trip.travelStyle?.length) exportText += `   🎯 ${trip.travelStyle.join(', ')}\n`;
      exportText += '\n';
    });

    exportText += `\n📊 Total: ${totalTrips} trips · ${uniqueCountries} countries · ${totalDays} days\n`;
    exportText += '\nGenerated by TripCraft - Your AI Travel Planner';

    try {
      await Share.share({
        message: exportText,
        title: 'My TripCraft Trips',
      });
    } catch (e) {
      // silent
    }
  };

  const s = getStyles(colors, typography);

  return (
    <SafeAreaView style={[s.container, { backgroundColor: colors.background }]}>
      <ScrollView showsVerticalScrollIndicator={false}>
        <View style={s.profileHeader}>
          <View style={[s.avatar, { backgroundColor: colors.primaryLight }]}>
            {user?.avatar ? (
              <Image source={{ uri: user.avatar }} style={s.avatarImage} />
            ) : (
              <Ionicons name="person" size={40} color={colors.textMuted} />
            )}
          </View>
          <Text style={[s.name, { color: colors.textPrimary }]}>{user?.name || 'Traveler'}</Text>
          <Text style={[s.email, { color: colors.textSecondary }]}>{user?.email || ''}</Text>
        </View>

        {/* Stats */}
        <View style={[s.statsCard, { backgroundColor: colors.card }]}>
          <Text style={[s.statsTitle, { color: colors.textSecondary }]}>Trip Stats</Text>
          <View style={s.statsRow}>
            {stats.map((stat) => (
              <View key={stat.label} style={s.statItem}>
                <Ionicons name={stat.icon} size={20} color={colors.primary} style={{ marginBottom: 4 }} />
                <Text style={[s.statValue, { color: colors.primary }]}>{stat.value}</Text>
                <Text style={[s.statLabel, { color: colors.textMuted }]}>{stat.label}</Text>
              </View>
            ))}
          </View>
        </View>

        {/* Settings */}
        <Text style={[s.sectionTitle, { color: colors.textSecondary }]}>Settings</Text>
        <View style={[s.menuCard, { backgroundColor: colors.card }]}>
          {/* Currency */}
          <TouchableOpacity style={[s.menuItem, s.menuItemBorder]} onPress={() => setShowCurrencyPicker(true)}>
            <Ionicons name="cash-outline" size={22} color={colors.textSecondary} />
            <Text style={[s.menuLabel, { color: colors.textPrimary }]}>Default Currency</Text>
            <Text style={[s.menuValue, { color: colors.textSecondary }]}>{currency}</Text>
            <Ionicons name="chevron-forward" size={18} color={colors.textMuted} />
          </TouchableOpacity>

          {/* Dark Mode */}
          <View style={[s.menuItem, s.menuItemBorder]}>
            <Ionicons name="moon-outline" size={22} color={colors.textSecondary} />
            <Text style={[s.menuLabel, { color: colors.textPrimary }]}>Dark Mode</Text>
            <Switch
              value={darkMode}
              onValueChange={toggleDarkMode}
              trackColor={{ false: colors.border, true: colors.primary }}
              thumbColor="#FFFFFF"
            />
          </View>

          {/* Notifications */}
          <View style={[s.menuItem, s.menuItemBorder]}>
            <Ionicons name="notifications-outline" size={22} color={colors.textSecondary} />
            <Text style={[s.menuLabel, { color: colors.textPrimary }]}>Notifications</Text>
            <Text style={[s.menuValue, { color: colors.textMuted }]}>Coming soon</Text>
          </View>

          {/* Export */}
          <TouchableOpacity style={s.menuItem} onPress={handleExport}>
            <Ionicons name="share-outline" size={22} color={colors.textSecondary} />
            <Text style={[s.menuLabel, { color: colors.textPrimary }]}>Export Trips</Text>
            <Ionicons name="chevron-forward" size={18} color={colors.textMuted} />
          </TouchableOpacity>
        </View>

        {/* About */}
        <View style={[s.menuCard, { backgroundColor: colors.card }]}>
          <TouchableOpacity style={[s.menuItem, s.menuItemBorder]} onPress={() => setShowAbout(true)}>
            <Ionicons name="information-circle-outline" size={22} color={colors.textSecondary} />
            <Text style={[s.menuLabel, { color: colors.textPrimary }]}>About TripCraft</Text>
            <Ionicons name="chevron-forward" size={18} color={colors.textMuted} />
          </TouchableOpacity>
          <TouchableOpacity style={[s.menuItem, s.menuItemBorder]} onPress={() => {
            Share.share({ message: 'Check out TripCraft - AI-powered solo travel planner! Plan your perfect trip in minutes.' });
          }}>
            <Ionicons name="chatbubble-outline" size={22} color={colors.textSecondary} />
            <Text style={[s.menuLabel, { color: colors.textPrimary }]}>Tell a Friend</Text>
            <Ionicons name="chevron-forward" size={18} color={colors.textMuted} />
          </TouchableOpacity>
          <TouchableOpacity style={s.menuItem} onPress={logout}>
            <Ionicons name="log-out-outline" size={22} color={colors.error} />
            <Text style={[s.menuLabel, { color: colors.error }]}>Log Out</Text>
          </TouchableOpacity>
        </View>

        <Text style={[s.version, { color: colors.textMuted }]}>TripCraft v1.0.0</Text>
        <View style={{ height: 100 }} />
      </ScrollView>

      {/* Currency Picker */}
      <SwipeableBottomSheet visible={showCurrencyPicker} onClose={() => setShowCurrencyPicker(false)} maxHeightRatio={0.6}>
        <Text style={[s.modalTitle, { color: colors.textPrimary }]}>Select Currency</Text>
        {currencies.map((c) => (
          <TouchableOpacity
            key={c}
            style={[s.currencyItem, currency === c && { backgroundColor: colors.primaryLight }]}
            onPress={() => {
              updateCurrency(c);
              setShowCurrencyPicker(false);
            }}
          >
            <Text style={[s.currencyText, { color: colors.textPrimary }, currency === c && { color: colors.primary, fontWeight: '700' }]}>{c}</Text>
            {currency === c && <Ionicons name="checkmark" size={22} color={colors.primary} />}
          </TouchableOpacity>
        ))}
      </SwipeableBottomSheet>

      {/* About */}
      <SwipeableBottomSheet visible={showAbout} onClose={() => setShowAbout(false)} maxHeightRatio={0.75}>
        <ScrollView showsVerticalScrollIndicator={false}>
          <View style={s.aboutHeader}>
            <View style={[s.aboutLogo, { backgroundColor: colors.primaryLight }]}>
              <Ionicons name="airplane" size={32} color={colors.primary} />
            </View>
            <Text style={[s.aboutTitle, { color: colors.textPrimary }]}>TripCraft</Text>
            <Text style={[s.aboutVersion, { color: colors.textMuted }]}>Version 1.0.0</Text>
          </View>
          <Text style={[s.aboutText, { color: colors.textSecondary }]}>
            TripCraft is your AI-powered solo travel companion. Plan perfect trips with personalized itineraries, smart budget tracking, interactive maps, and curated packing lists.
          </Text>
          <Text style={[s.aboutText, { color: colors.textSecondary, marginTop: spacing.md }]}>
            Built with React Native, Expo, Node.js, MongoDB, and OpenAI.
          </Text>
          <View style={s.aboutFeatures}>
            {[
              { icon: 'sparkles', text: 'AI-Generated Itineraries' },
              { icon: 'map', text: 'Interactive Maps' },
              { icon: 'wallet', text: 'Budget Tracking' },
              { icon: 'bag', text: 'Smart Packing Lists' },
              { icon: 'sunny', text: 'Weather Forecasts' },
              { icon: 'pencil', text: 'Edit & Customize' },
            ].map((f) => (
              <View key={f.text} style={s.aboutFeatureRow}>
                <Ionicons name={f.icon} size={18} color={colors.primary} />
                <Text style={[s.aboutFeatureText, { color: colors.textPrimary }]}>{f.text}</Text>
              </View>
            ))}
          </View>
        </ScrollView>
      </SwipeableBottomSheet>
    </SafeAreaView>
  );
}

const getStyles = (colors, typography) => StyleSheet.create({
  container: {
    flex: 1,
    padding: spacing.xl,
  },
  profileHeader: {
    alignItems: 'center',
    marginBottom: spacing.xxl,
  },
  avatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  avatarImage: {
    width: 80,
    height: 80,
    borderRadius: 40,
  },
  name: {
    fontSize: 22,
    fontWeight: '700',
    marginBottom: spacing.xs,
  },
  email: {
    fontSize: 14,
  },
  statsCard: {
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
    marginBottom: spacing.xxl,
    ...shadows.card,
  },
  statsTitle: {
    fontSize: 14,
    fontWeight: '600',
    marginBottom: spacing.lg,
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  statItem: {
    alignItems: 'center',
  },
  statValue: {
    fontSize: 22,
    fontWeight: '700',
  },
  statLabel: {
    fontSize: 12,
    marginTop: spacing.xs,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '600',
    marginBottom: spacing.md,
  },
  menuCard: {
    borderRadius: borderRadius.lg,
    marginBottom: spacing.lg,
    ...shadows.card,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: spacing.lg,
    gap: spacing.md,
  },
  menuItemBorder: {
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  menuLabel: {
    fontSize: 16,
    flex: 1,
  },
  menuValue: {
    fontSize: 14,
    marginRight: spacing.sm,
  },
  version: {
    textAlign: 'center',
    fontSize: 12,
    marginTop: spacing.md,
  },
  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  modalSheet: {
    borderTopLeftRadius: borderRadius.xl,
    borderTopRightRadius: borderRadius.xl,
    padding: spacing.xl,
    maxHeight: '80%',
  },
  modalHandle: {
    width: 40,
    height: 4,
    backgroundColor: '#E5E7EB',
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: spacing.lg,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '700',
    marginBottom: spacing.lg,
  },
  currencyItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: spacing.lg,
    borderRadius: borderRadius.md,
    marginBottom: spacing.xs,
  },
  currencyText: {
    fontSize: 16,
  },
  modalCancel: {
    alignItems: 'center',
    paddingVertical: spacing.lg,
    marginTop: spacing.md,
  },
  modalCancelText: {
    fontSize: 16,
    fontWeight: '600',
  },
  // About
  aboutHeader: {
    alignItems: 'center',
    marginBottom: spacing.xxl,
  },
  aboutLogo: {
    width: 64,
    height: 64,
    borderRadius: 32,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  aboutTitle: {
    fontSize: 24,
    fontWeight: '700',
  },
  aboutVersion: {
    fontSize: 14,
    marginTop: spacing.xs,
  },
  aboutText: {
    fontSize: 14,
    lineHeight: 22,
    textAlign: 'center',
  },
  aboutFeatures: {
    marginTop: spacing.xxl,
    gap: spacing.md,
  },
  aboutFeatureRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
  },
  aboutFeatureText: {
    fontSize: 15,
  },
});
