export const COUNTRIES = [
  { name: 'Tokyo', country: 'Japan', emoji: '🗼' },
  { name: 'Paris', country: 'France', emoji: '🗼' },
  { name: 'London', country: 'UK', emoji: '🇬🇧' },
  { name: 'New York', country: 'USA', emoji: '🗽' },
  { name: 'Dubai', country: 'UAE', emoji: '🏙' },
  { name: 'Singapore', country: 'Singapore', emoji: '🇸🇬' },
  { name: 'Bangkok', country: 'Thailand', emoji: '🛕' },
  { name: 'Istanbul', country: 'Turkey', emoji: '🕌' },
  { name: 'Rome', country: 'Italy', emoji: '🏛' },
  { name: 'Barcelona', country: 'Spain', emoji: '⛪' },
  { name: 'Amsterdam', country: 'Netherlands', emoji: '🌷' },
  { name: 'Sydney', country: 'Australia', emoji: '🦘' },
  { name: 'Seoul', country: 'South Korea', emoji: '🇰🇷' },
  { name: 'Bali', country: 'Indonesia', emoji: '🌴' },
  { name: 'Maldives', country: 'Maldives', emoji: '🏝' },
  { name: 'Cairo', country: 'Egypt', emoji: '🏺' },
  { name: 'Cape Town', country: 'South Africa', emoji: '🌍' },
  { name: 'Rio de Janeiro', country: 'Brazil', emoji: '🎭' },
  { name: 'Machu Picchu', country: 'Peru', emoji: '🏔' },
  { name: 'Santorini', country: 'Greece', emoji: '🏖' },
  { name: 'Prague', country: 'Czech Republic', emoji: '🏰' },
  { name: 'Vienna', country: 'Austria', emoji: '🎵' },
  { name: 'Zurich', country: 'Switzerland', emoji: '⛷' },
  { name: 'Reykjavik', country: 'Iceland', emoji: '🧊' },
  { name: 'Marrakech', country: 'Morocco', emoji: '🕌' },
  { name: 'Nairobi', country: 'Kenya', emoji: '🦁' },
  { name: 'Havana', country: 'Cuba', emoji: '🚗' },
  { name: 'Mexico City', country: 'Mexico', emoji: '🌮' },
  { name: 'Lisbon', country: 'Portugal', emoji: '🚃' },
  { name: 'Berlin', country: 'Germany', emoji: '🇩🇪' },
  { name: 'Athens', country: 'Greece', emoji: '🏛' },
  { name: 'Budapest', country: 'Hungary', emoji: '♨️' },
  { name: 'Hanoi', country: 'Vietnam', emoji: '🍜' },
  { name: 'Kuala Lumpur', country: 'Malaysia', emoji: '🇲🇾' },
  { name: 'Petra', country: 'Jordan', emoji: '🏜' },
  { name: 'Colombo', country: 'Sri Lanka', emoji: '🏝' },
  { name: 'Kathmandu', country: 'Nepal', emoji: '🏔' },
  { name: 'Queenstown', country: 'New Zealand', emoji: '🏔' },
  { name: 'Zanzibar', country: 'Tanzania', emoji: '🏖' },
  { name: 'Dubrovnik', country: 'Croatia', emoji: '⛵' },
  { name: 'Cusco', country: 'Peru', emoji: '🏔' },
  { name: 'Bruges', country: 'Belgium', emoji: '🍫' },
  { name: 'Helsinki', country: 'Finland', emoji: '🇫🇮' },
  { name: 'Oslo', country: 'Norway', emoji: '🇳🇴' },
  { name: 'Stockholm', country: 'Sweden', emoji: '🇸🇪' },
  { name: 'Copenhagen', country: 'Denmark', emoji: '🇩🇰' },
  { name: 'Edinburgh', country: 'Scotland', emoji: '🏴' },
  { name: 'Dublin', country: 'Ireland', emoji: '☘️' },
  { name: 'Moscow', country: 'Russia', emoji: '🏰' },
  { name: 'Osaka', country: 'Japan', emoji: '🍣' },
  { name: 'Kyoto', country: 'Japan', emoji: '⛩' },
  { name: 'Hong Kong', country: 'China', emoji: '🌃' },
  { name: 'Shanghai', country: 'China', emoji: '🏙' },
  { name: 'Beijing', country: 'China', emoji: '🏯' },
  { name: 'Taipei', country: 'Taiwan', emoji: '🏮' },
  { name: 'Buenos Aires', country: 'Argentina', emoji: '💃' },
  { name: 'Santiago', country: 'Chile', emoji: '🏔' },
  { name: 'Bogota', country: 'Colombia', emoji: '☕' },
  { name: 'Lima', country: 'Peru', emoji: '🍽' },
  { name: 'Cartagena', country: 'Colombia', emoji: '🏖' },
  { name: 'Toronto', country: 'Canada', emoji: '🍁' },
  { name: 'Vancouver', country: 'Canada', emoji: '🏔' },
  { name: 'San Francisco', country: 'USA', emoji: '🌉' },
  { name: 'Los Angeles', country: 'USA', emoji: '🎬' },
  { name: 'Las Vegas', country: 'USA', emoji: '🎰' },
  { name: 'Phuket', country: 'Thailand', emoji: '🏖' },
  { name: 'Chiang Mai', country: 'Thailand', emoji: '🛕' },
  { name: 'Siem Reap', country: 'Cambodia', emoji: '🏛' },
  { name: 'Luang Prabang', country: 'Laos', emoji: '🛕' },
  { name: 'Tbilisi', country: 'Georgia', emoji: '🏔' },
  { name: 'Tashkent', country: 'Uzbekistan', emoji: '🕌' },
  { name: 'Samarkand', country: 'Uzbekistan', emoji: '🏛' },
  { name: 'Muscat', country: 'Oman', emoji: '🏜' },
  { name: 'Doha', country: 'Qatar', emoji: '🏙' },
  { name: 'Abu Dhabi', country: 'UAE', emoji: '🕌' },
  { name: 'Casablanca', country: 'Morocco', emoji: '🕌' },
  { name: 'Fez', country: 'Morocco', emoji: '🏺' },
  { name: 'Accra', country: 'Ghana', emoji: '🌍' },
  { name: 'Lagos', country: 'Nigeria', emoji: '🌍' },
  { name: 'Kigali', country: 'Rwanda', emoji: '🌍' },
  { name: 'Victoria Falls', country: 'Zimbabwe', emoji: '💧' },
  { name: 'Windhoek', country: 'Namibia', emoji: '🏜' },
  { name: 'Mauritius', country: 'Mauritius', emoji: '🏝' },
  { name: 'Seychelles', country: 'Seychelles', emoji: '🏝' },
  { name: 'Fiji', country: 'Fiji', emoji: '🏝' },
  { name: 'Bora Bora', country: 'French Polynesia', emoji: '🏝' },
  { name: 'Patagonia', country: 'Argentina', emoji: '🏔' },
  { name: 'Galapagos', country: 'Ecuador', emoji: '🐢' },
  { name: 'Bruges', country: 'Belgium', emoji: '🍫' },
  { name: 'Nice', country: 'France', emoji: '🌊' },
  { name: 'Amalfi Coast', country: 'Italy', emoji: '🌊' },
  { name: 'Florence', country: 'Italy', emoji: '🎨' },
  { name: 'Venice', country: 'Italy', emoji: '🛶' },
  { name: 'Milan', country: 'Italy', emoji: '👗' },
  { name: 'Munich', country: 'Germany', emoji: '🍺' },
  { name: 'Salzburg', country: 'Austria', emoji: '🎵' },
  { name: 'Interlaken', country: 'Switzerland', emoji: '🏔' },
  { name: 'Lake Bled', country: 'Slovenia', emoji: '🏞' },
  { name: 'Split', country: 'Croatia', emoji: '🏖' },
];

export const INDIAN_STATES = [
  { name: 'Goa', country: 'India', emoji: '🏖' },
  { name: 'Manali', country: 'India', emoji: '🏔' },
  { name: 'Shimla', country: 'India', emoji: '🏔' },
  { name: 'Jaipur', country: 'India', emoji: '🏰' },
  { name: 'Udaipur', country: 'India', emoji: '🏰' },
  { name: 'Rishikesh', country: 'India', emoji: '🧘' },
  { name: 'Varanasi', country: 'India', emoji: '🛕' },
  { name: 'Kerala', country: 'India', emoji: '🌴' },
  { name: 'Ladakh', country: 'India', emoji: '🏔' },
  { name: 'Darjeeling', country: 'India', emoji: '🍵' },
  { name: 'Agra', country: 'India', emoji: '🕌' },
  { name: 'Delhi', country: 'India', emoji: '🏛' },
  { name: 'Mumbai', country: 'India', emoji: '🌃' },
  { name: 'Kolkata', country: 'India', emoji: '🏛' },
  { name: 'Chennai', country: 'India', emoji: '🛕' },
  { name: 'Bangalore', country: 'India', emoji: '💻' },
  { name: 'Hyderabad', country: 'India', emoji: '🕌' },
  { name: 'Pune', country: 'India', emoji: '🏙' },
  { name: 'Amritsar', country: 'India', emoji: '🛕' },
  { name: 'Jodhpur', country: 'India', emoji: '🏰' },
  { name: 'Jaisalmer', country: 'India', emoji: '🏜' },
  { name: 'Ooty', country: 'India', emoji: '🌿' },
  { name: 'Kodaikanal', country: 'India', emoji: '🌿' },
  { name: 'Munnar', country: 'India', emoji: '🍵' },
  { name: 'Hampi', country: 'India', emoji: '🏛' },
  { name: 'Mysore', country: 'India', emoji: '🏰' },
  { name: 'Coorg', country: 'India', emoji: '🌿' },
  { name: 'Andaman', country: 'India', emoji: '🏝' },
  { name: 'Lakshadweep', country: 'India', emoji: '🏝' },
  { name: 'Sikkim', country: 'India', emoji: '🏔' },
  { name: 'Meghalaya', country: 'India', emoji: '🌧' },
  { name: 'Arunachal Pradesh', country: 'India', emoji: '🏔' },
  { name: 'Kasol', country: 'India', emoji: '🏔' },
  { name: 'McLeod Ganj', country: 'India', emoji: '🏔' },
  { name: 'Spiti Valley', country: 'India', emoji: '🏔' },
  { name: 'Rann of Kutch', country: 'India', emoji: '🏜' },
  { name: 'Alleppey', country: 'India', emoji: '🛶' },
  { name: 'Pondicherry', country: 'India', emoji: '🏖' },
  { name: 'Mahabalipuram', country: 'India', emoji: '🏛' },
  { name: 'Khajuraho', country: 'India', emoji: '🏛' },
  { name: 'Nainital', country: 'India', emoji: '🏞' },
  { name: 'Mussoorie', country: 'India', emoji: '🏔' },
  { name: 'Leh', country: 'India', emoji: '🏔' },
  { name: 'Srinagar', country: 'India', emoji: '🌸' },
  { name: 'Gulmarg', country: 'India', emoji: '⛷' },
  { name: 'Pahalgam', country: 'India', emoji: '🏔' },
  { name: 'Mount Abu', country: 'India', emoji: '🏔' },
  { name: 'Pushkar', country: 'India', emoji: '🐪' },
  { name: 'Ajmer', country: 'India', emoji: '🕌' },
  { name: 'Bodh Gaya', country: 'India', emoji: '🛕' },
];

// Get random unique suggestions mixing countries and Indian states
// Uses spread copies to avoid mutating the exported const arrays
export function getRandomSuggestions(count = 10) {
  const indian = [...INDIAN_STATES].sort(() => Math.random() - 0.5).slice(0, 4);
  const international = [...COUNTRIES].sort(() => Math.random() - 0.5).slice(0, 6);

  return [...indian, ...international].sort(() => Math.random() - 0.5).slice(0, count);
}
